languageCode = 'en-gb'
title = 'gotofritz'
theme = 'hugo-bearblog'

# to use --- for frontmatter
metaDataFormat = "yaml"

enableRobotsTXT = true

[params]
archetype = "default"
defaultType = "post"
favicon = "icon.svg"
faviconLegacy = "favicon.ico"
faviconAppleTouch = "apple-touch-icon.png"

[markup]
  [markup.goldmark]
	renderer.unsafe = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
	minifyOutput = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'