#!/bin/bash

# Check if TITLE is provided
if [ -z "$1" ]; then
  echo "Usage: $0 \"Your Title Here\""
  exit 1
fi

TITLE="$1"

# URLize the title (convert to lowercase, replace spaces with hyphens)
URLIZED_TITLE=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9-]/-/g' | sed 's/-*$//')

PATH_TO_POST="content/blog/$(date +%Y-%m-%d)-$URLIZED_TITLE"

# Create the blog post
hugo new "$PATH_TO_POST/index.md"

echo ""
echo "To create a different image:"
echo "create-glitch-preview \"$PATH_TO_POST/feature.png\""

create-glitch-preview "$PATH_TO_POST/feature.png"
